server:
  port: 8080
  servlet:
    context-path: /
    
im:
  socket:
    host: 127.0.0.1
    port: 9901
    # 消息发送失败时，重试次数
    retry: 3
#    roomId: default

# spring配置
spring:
  application:
    name: YI-IM
  main:
    allow-bean-definition-overriding: true
  mvc:
    # 出现错误时, 直接抛出异常
    throw-exception-if-no-handler-found: true
    servlet:
      load-on-startup: 0
    static-path-pattern: /static/**
  resources:
    static-locations: file:E:/idea-workspace/YI-IM/im-demo/im-demo1/src/main/resources/static/
#    static-locations: classpath:/static/
  freemarker:
    templateLoaderPath: classpath:/templates/
    suffix: .html
    charset: UTF-8
    request-context-attribute: request
    settings.number_format: 0.##########
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    #password:
    timeout: 3600ms
    #    cluster:
    #      max-redirects: 3
    #      nodes: 127.0.0.1:7000, 127.0.0.1:7001, 127.0.0.1:7002, 127.0.0.1:7003, 127.0.0.1:7004,127.0.0.1:7005
    lettuce:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 50
        max-wait: 6000ms
      shutdown-timeout: 100ms
